name: Deploy Nutri-AS Pro

on:
  push:
    branches:
      - main # ðŸ‘ˆ Se activa solo al hacer push a esta rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegando en VPS vÃ­a SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY_NUTRIAS }}
          port: 22
          script: |
            cd /var/www/nutri-as
            git pull 
            npm install
            npm run build
            pm2 restart nutri-as --update-env